apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applications-getter
rules:
  - apiGroups: ["app.k8s.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "create", "delete", "deletecollection", "patch", "update"]
