application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  image.image:
    type: string
    default: gcr.io/silent-vim-415621/redis:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: image.repo
            after: image.tag
required:
- name
- namespace
- image.image
