apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: &Labels
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: redis-to-vertex-ai-search
    app: {{ template "redis-to-vertex-ai-search.name" . }}
    chart: {{ template "redis-to-vertex-ai-search.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: redis-to-vertex-ai-search
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
