apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app: {{ template "redis-to-vertex-ai-search.name" . }}
    chart: {{ template "redis-to-vertex-ai-search.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "redis-to-vertex-ai-search.name" . }}
    release: {{ .Release.Name }}
